#!/usr/bin/env python3
"""
gen_probe.py -- generate the v2 broadband probe signal for surround-probe.

Emits (run from the surround-probe root, i.e. `python3 tools/gen_probe.py`):
  * source/probe_buf.h   -- a `static const short g_probe[PROBE_NSAMP]` table the
                            homebrew memcpy's into the DSP wave buffer. No on-device
                            FFT or libm; the signal is bit-identical every boot.
  * tools/probe_ref.wav  -- the same one period as a mono WAV, for reference/audit.

Signal: one period of a PERIODIC, band-limited (100 Hz .. 14 kHz) PINK-weighted
multitone with SCHROEDER phase. Periodic-by-construction => the DSP wave buffer
loops seamlessly (no per-loop click) and every >=1-period window of a recording
holds the SAME realization (up to a circular shift), which is what lets the
analyzer compare segments captured at different times. Schroeder phase is
deterministic (no RNG, reproducible header) and near-constant-envelope, so
split_run.py's energy-envelope segmentation stays clean and no median smoothing
is needed. Broadband + (in the app) hard-corner routing is what lets v2 resolve
the front/back virtualization v1's steady centered tone was blind to.
"""
import struct
import numpy as np

SR   = 32728            # DSP native rate (no resampler in the device path)
N    = 16384            # period = N/SR = 0.5008 s ; f0 = SR/N = 1.9976 Hz
FLO  = 100.0
FHI  = 14000.0
PEAK = 0.35             # normalize to -9 dBFS peak: headroom for a surround sum

def main():
    f0 = SR / N
    k = np.arange(N // 2 + 1)
    freq = k * f0
    band = (freq >= FLO) & (freq <= FHI)
    band[0] = False
    band[-1] = False                      # never excite DC or Nyquist

    mag = np.zeros(k.size)
    mag[band] = 1.0 / np.sqrt(freq[band])  # pink: -3 dB/octave

    # Schroeder phase over the M excited bins, in increasing-frequency order.
    idx = np.nonzero(band)[0]
    M = idx.size
    phase = np.zeros(k.size)
    m = np.arange(1, M + 1)
    phase[idx] = -np.pi * m * (m - 1) / M

    x = np.fft.irfft(mag * np.exp(1j * phase), N)
    crest = np.max(np.abs(x)) / np.sqrt(np.mean(x * x))
    x = x / np.max(np.abs(x)) * PEAK
    pcm = np.round(x * 32767.0).astype("<i2")

    with open("source/probe_buf.h", "w", newline="\n") as f:
        f.write(f"// generated by tools/gen_probe.py -- do not hand-edit\n")
        f.write(f"// N={N} SR={SR} band={FLO:.0f}-{FHI:.0f}Hz phase=Schroeder "
                f"M={M} crest={crest:.3f} peak={PEAK}\n")
        f.write(f"#define PROBE_NSAMP {N}\n")
        f.write("static const short g_probe[PROBE_NSAMP] = {\n")
        for i in range(0, N, 16):
            f.write("  " + ",".join(str(int(v)) for v in pcm[i:i + 16]) + ",\n")
        f.write("};\n")

    d = pcm.tobytes()
    with open("tools/probe_ref.wav", "wb") as f:
        f.write(b"RIFF" + struct.pack("<I", 36 + len(d)) + b"WAVE")
        f.write(b"fmt " + struct.pack("<IHHIIHH", 16, 1, 1, SR, SR * 2, 2, 16))
        f.write(b"data" + struct.pack("<I", len(d)) + d)

    print(f"wrote source/probe_buf.h ({N} samples, {M} tones, crest {crest:.2f}) "
          f"and tools/probe_ref.wav")


if __name__ == "__main__":
    main()
